# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Doumentação Funcional - Site Café Ariany
title-short: Café Ariany
email: levi.esteves@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Para fins gerais foi criada esta documentação funcional do site "Café Ariany". Esta documentação demonstra os passos para a configuração de sua estrutura via painel administrativo do Wordpress.
baseurl: "/clientes/cafeariany" # the subpath of your site, e.g. /blog
url: "http://cafearinay.com.br" # the base hostname & protocol for your site
twitter_username: cafeariany
github_username:  levismad
weight: 9999999
# Build settings
markdown: kramdown
paginate: 5
gems: [jekyll-paginate]